server:
  port: 8080
  servlet:
    context-path: /auction

spring:
  datasource:
    # Đã thêm ?createDatabaseIfNotExist=true vào cuối url
    url: "jdbc:mysql://localhost:3306/AuctionBidSystemTest?createDatabaseIfNotExist=true"
    username: root
    password: root

  # ĐOẠN NÀY ĐỂ CHẠY FILE SCHEMA.SQL
  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: none # Giữ nguyên là 'none' để tắt Hibernate tự đẻ bảng
    show-sql: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB