name: Spring Boot CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest 

    # ============================================================
    # CHỈ ĐƯỜNG CHO ROBOT: Mọi lệnh run phải chui vào thư mục này
    # ============================================================
    defaults:
      run:
        working-directory: ./AuctionBidSystemSpringBootRework

    # Giả lập Database
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: AuctionBidSystemTest
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: 1. Lấy code từ GitHub về máy ảo
      uses: actions/checkout@v4

    - name: 2. Cài đặt Java 25
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'
        cache: maven

    - name: 3. Chạy Đóng gói (Package)
      run: mvn clean package

    - name: 4. Chạy JUnit Test
      run: mvn test

    - name: 5. Lưu trữ file JAR (Artifact) để tải về
      if: success() 
      uses: actions/upload-artifact@v4
      with:
        name: auction-backend-jar
        # Chú ý đường dẫn lấy file JAR cũng phải thêm thư mục con vào
        path: AuctionBidSystemSpringBootRework/target/*.jar
